service: backend

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  region: eu-central-1
  stage: ${opt:stage, 'dev'}
  environment:
    NODE_ENV: ${self:provider.stage}
    MONGODB_URI: ${ssm:/backend/${self:provider.stage}/MONGODB_URI}
    ADMIN_USERNAME: ${ssm:/backend/${self:provider.stage}/ADMIN_USERNAME}
    ADMIN_PASSWORD: ${ssm:/backend/${self:provider.stage}/ADMIN_PASSWORD}
    JWT_SECRET: ${ssm:/backend/${self:provider.stage}/JWT_SECRET}

plugins:
  - serverless-plugin-typescript
  - serverless-offline

functions:
  api:
    handler: index.handler
    timeout: 30
    events:
      - http:
          path: /{proxy+}
          method: ANY
          cors: true
      - http:
          path: /
          method: ANY
          cors: true

package:
  exclude:
    - .git/**
    - src/**/*.test.ts
    - jest.config.js
    - tsconfig.json